import React from 'react';
import { GetServerSidePropsContext, NextPage } from 'next';
import Head from 'next/head';

import { postsService } from '@/services';
import { PostsProvider } from '@/contexts';
import type { Post } from '@/screens/home/types';

import { RootLayout } from '@/layouts';
import { Home } from '@/screens';

interface HomePageProps {
  posts: Post[];
}

const HomePage: NextPage<HomePageProps> & {
  getLayout: (page: React.ReactNode) => React.ReactNode;
} = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Blogging app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <PostsProvider postList={posts}>
        <Home />
      </PostsProvider>
    </>
  );
};

HomePage.getLayout = (page: React.ReactNode) => {
  return <RootLayout>{page}</RootLayout>;
};

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const { posts } = await postsService.getPosts(ctx);

  return {
    props: {
      posts,
    },
  };
};

export default HomePage;
