import Head from 'next/head';

import { RootLayout } from '@/layouts';
import { Home } from '@/screens';

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Blogging app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Home />
    </>
  );
};

HomePage.getLayout = (page: React.ReactNode) => {
  return <RootLayout>{page}</RootLayout>;
};

export default HomePage;
